/**
 * All API return codes
 */
module.exports = {
  auth: {
    JWT_MISSING: 'JWT_MISSING',
    JWT_INVALID: 'JWT_INVALID',
    JWT_MALFORMED: 'JWT_MALFORMED',
    ROLE_NOT_PROVIDED: 'ROLE_NOT_PROVIDED',
    EMAIL_PASSWORD_NOT_PROVIDED: 'EMAIL_PASSWORD_NOT_PROVIDED',
    NEW_PASSWORD_NOT_PROVIDED: 'NEW_PASSWORD_NOT_PROVIDED',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    REGISTRATION_SUCCESSFULL: 'REGISTRATION_SUCCESSFULL',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    USER_DOES_NOT_EXIST: 'USER_DOES_NOT_EXIST',
    INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    USER_BANNED: 'USER_BANNED',
    USER_DELETED: 'USER_DELETED',
    PROFILE_NOT_APPROVED: 'PROFILE_NOT_APPROVED',
    LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
    PASSWORD_CHANGED_SUCCESSFULLY: 'PASSWORD_CHANGED_SUCCESSFULLY',
    NEW_TOKEN_SUCCESSFUL: 'NEW_TOKEN_SUCCESSFUL',
    WEAK_PASSWORD: 'WEAK_PASSWORD',
    REGISTRATION_FAILED: 'REGISTRATION_FAILED',
    CHANGE_PASSWORD_FAILED: 'CHANGE_PASSWORD_FAILED',
    RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED',
    LOGIN_FAILED: 'LOGIN_FAILED',
    EMAIL_CHANGE_FAILED: 'EMAIL_CHANGE_FAILED',
    EMAIL_INVALID: 'EMAIL_INVALID',
    SUCCESS: 'SUCCESS',
    INVALID_QUERY_PARAMS_FORMAT: 'INVALID_QUERY_PARAMS_FORMAT'
  },
  token: {
    NAME_ALREADY_EXISTS : 'NAME_ALREADY_EXISTS',
    RESOURCE_DONT_EXIST : 'RESOURCE_DONT_EXIST',
    FORBIDDEN_ACCESS : 'FORBIDDEN_ACCESS',
    ALREADY_APPROVED : 'ALREADY_APPROVED',
    INSUFFICIENT_FUNDS : 'INSUFFICIENT_FUNDS'
  }
};
